# These are supported funding model platforms

github: [GeauxWeisbeck4]
ko_fi: [andrewweisbeck4](https://ko-fi.com/andrewweisbeck4)
patreon: [andrewweisbeck4](https://patreon.com/andrewweisbeck4?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink)
